### ISSUE TITLE
Add flight SQL to pip install 

### ISSUE THREAD

**Issue by Anaisdg** [InfluxCommunity/influxdb3-python-cli#5]
Pip instillation is successful.
```
Collecting influxdb3-python-cli
  Downloading influxdb3_python_cli-0.1.1-py3-none-any.whl (12 kB)
Collecting influxdb3-python
  Downloading influxdb3_python-0.1.4-py3-none-any.whl (9.0 kB)
Collecting pathlib
  Downloading pathlib-1.0.1-py3-none-any.whl (14 kB)
Collecting pygments
  Downloading Pygments-2.15.1-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 4.2 MB/s eta 0:00:00
Collecting prompt-toolkit
  Downloading prompt_toolkit-3.0.38-py3-none-any.whl (385 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.8/385.8 kB 16.3 MB/s eta 0:00:00
Collecting pandas
  Downloading pandas-2.0.2-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 14.6 MB/s eta 0:00:00
Collecting tabulate
  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)
Collecting pyarrow
  Downloading pyarrow-12.0.0-cp311-cp311-macosx_11_0_arm64.whl (22.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.6/22.6 MB 13.8 MB/s eta 0:00:00
Collecting influxdb-client
  Downloading influxdb_client-1.36.1-py3-none-any.whl (721 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 721.2/721.2 kB 12.2 MB/s eta 0:00:00
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 8.0 MB/s eta 0:00:00
Collecting pytz>=2020.1
  Downloading pytz-2023.3-py2.py3-none-any.whl (502 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 502.3/502.3 kB 13.6 MB/s eta 0:00:00
Collecting tzdata>=2022.1
  Downloading tzdata-2023.3-py2.py3-none-any.whl (341 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 13.0 MB/s eta 0:00:00
Collecting numpy>=1.21.0
  Downloading numpy-1.24.3-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 14.3 MB/s eta 0:00:00
Collecting wcwidth
  Downloading wcwidth-0.2.6-py2.py3-none-any.whl (29 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting reactivex>=4.0.4
  Downloading reactivex-4.0.4-py3-none-any.whl (217 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 217.8/217.8 kB 7.1 MB/s eta 0:00:00
Requirement already satisfied: certifi>=14.05.14 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from influxdb-client->influxdb3-python->influxdb3-python-cli) (2023.5.7)
Requirement already satisfied: setuptools>=21.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from influxdb-client->influxdb3-python->influxdb3-python-cli) (65.5.0)
Collecting urllib3>=1.26.0
  Downloading urllib3-2.0.3-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.6/123.6 kB 18.7 MB/s eta 0:00:00
Collecting typing-extensions<5.0.0,>=4.1.1
  Downloading typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Installing collected packages: wcwidth, pytz, pathlib, urllib3, tzdata, typing-extensions, tabulate, six, pygments, prompt-toolkit, numpy, reactivex, python-dateutil, pyarrow, pandas, influxdb-client, influxdb3-python, influxdb3-python-cli
Successfully installed influxdb-client-1.36.1 influxdb3-python-0.1.4 influxdb3-python-cli-0.1.1 numpy-1.24.3 pandas-2.0.2 pathlib-1.0.1 prompt-toolkit-3.0.38 pyarrow-12.0.0 pygments-2.15.1 python-dateutil-2.8.2 pytz-2023.3 reactivex-4.0.4 six-1.16.0 tabulate-0.9.0 typing-extensions-4.6.3 tzdata-2023.3 urllib3-2.0.3 wcwidth-0.2.6
```
However when you try to use the CLI, I get the following error: 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/influx3", line 5, in <module>
    from influxdb_cli.influx3 import main
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/influxdb_cli/influx3.py", line 5, in <module>
    from flightsql import FlightSQLClient
ModuleNotFoundError: No module named 'flightsql'
anais@MacBook-Pro-2 ~ % influx3
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/influx3", line 5, in <module>
    from influxdb_cli.influx3 import main
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/influxdb_cli/influx3.py", line 5, in <module>
    from flightsql import FlightSQLClient
ModuleNotFoundError: No module named 'flightsql'
```

**Comment by Jayclifford345** [comment]
Thanks Anais! Resolved in latest version :)
